### ISSUE TITLE
Plus sign after index

### ISSUE THREAD

**Issue by DeaconOfBiology** [twlee79/filter_illumina_index#1]
Hello,
I would like to use your program to parse apart some reads with in my fastq.gz files. However, I have hit a hang up. The sequence identifier line in my fastq files looks like this: @VH00345:14:AAC3KVFHV:2:1101:46483:1000 1:N:0:TCTATCCTAA+CCAGTCGACG

The index I am interested in is the "TCTATCCTAA". However, the "+CCAGTCGACG" is causing filter_illumina_index to not see the specified index as the source code appears to not account for the possibility of this set up. Is there a way around this hang up, or would I need to modify the source code? Thanks for any information you can provide!

**Comment by twlee79** [comment]
As it stands the script only does sees the whole entry after the `:` as a single index, so you can't filter by the `TCTATCCTAA` only. I should be able to modify it to be more flexible, perhaps by allowing a regular expression for the index. I'll have a look into this.

**Comment by DeaconOfBiology** [comment]
Thanx! That capability would be awesome!

**Comment by DeondeJager** [comment]
I'd like to upvote this request :) I'd also like to see this feature added, to allow for dual-indexed libraries to be filtered in this way. Would be super helpful! 
Cheers,
Deon

**Comment by twlee79** [comment]
Thanks for the upvote. I will look into this week. Cheers

**Comment by twlee79** [comment]
This is now supported with 1.0.5. Two indexes are now supported with a user-defined separator. To filter by the `TCTATCCTAA`  in `TCTATCCTAA+CCAGTCGACG`, the following parameters should work: `--index TCTATCCTAA --index2 "" --separator +`

v1.0.5 has been packaged and is available in pip, and on conda on the twlee79 channel.
